# Site settings
title: NPA OpenROV
email: your-email@domain.com
description: "The Northcoast Prepatory and Performing Arts Academy OpenROV elective. This is a STEM program."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/nparov
  - title: facebook
    url: https://www.facebook.com/NPAOpenROV

# Postal address (add as many lines as necessary)
address:
  - line: P.O. Box 276
  - line: Arcata, CA 95518

# Build settings
markdown: kramdown
permalink: pretty
