# Site settings
title: NPA OpenROV
email: your-email@domain.com
description: "The Northcoast Prepatory and Performing Arts Academy OpenROV elective. This is a STEM program."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: sgoblin
  pic: https://upload.wikimedia.org/wikipedia/commons/2/26/Aliensmiley.svg
  position: Head of the Website Team
  easyName: headWebsite
  bioURI: team/headWebsite.md
  social:
    - title: github
      url: https://www.github.com/sgoblin
    - title: bitbucket
      url: https://bitbucket.org/sgoblin
- name: Leif
  pic: img/team/200px-cropped-Seattle's_Leif_Erikson_statue.jpg
  position: Chief Exploration Officer
  easyName: leif
  bioURI: team/ceo.md
  social:
    - title: eye
      url: https://en.wikipedia.org/wiki/Leif_Erikson
- name: Milo
  pic: img/team/milo200.jpg
  position: Member of the website team
  easyName: milo
  bioURI: team/milo.html
  social:
    - title: instagram
      url: http://instagram.com/wellerfeller
- name: Wyll
  pic: https://lh3.googleusercontent.com/-_m5FMk7zavw/AAAAAAAAAAI/AAAAAAAAAWY/7MNS5w0XQ1M/s120-c/photo.jpg
  position: Member of the website team, Drone pilot
  easyName: wyll
  bioURI: team/wyll.md
  social:
    - title: youtube
      url: https://www.youtube.com/user/Wyllsurfer
    - title: google-plus
      url: https://plus.google.com/u/0/109089429719375756207/posts
    - title: github
      url: https://github.com/wyllsurf
- name: Forest
  pic: //placekitten.com/200/200
  position: Member of the website team, Drone pilot
  easyName: forest
  bioURI: team/forest.md
  social:
- name: More coming soon
  pic: img/team/loading-spin.svg
  position: There is homework, click for more info
  easyName: soon
  bioURI: team/cs.txt
  social:
    - title: cog fa-spin
      url: https://www.youtube.com/watch?v=eFHdRkeEnpM

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/nparov
  - title: facebook
    url: https://www.facebook.com/NPAOpenROV

# Postal address (add as many lines as necessary)
address:
  - line: P.O. Box 276
  - line: Arcata, CA 95518

# Build settings
markdown: kramdown
permalink: pretty
